# This file contains values from Cookiecutter

default_context:
  project_name: "pdf-parser"
  project_description: "Parse the pdf and generate report"
  organization: "pdf-parser"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.9
  github_name: "parthi-siva"
  email: "parthimyself90@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
